// <auto-generated />
using System;
using BlackjackBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlackjackBot.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712093222_AddDaily")]
    partial class AddDaily
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlackjackBot.Domain.Entities.GameHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientSeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServerSeedHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("BlackjackBot.Domain.Entities.Player", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("BjDraws")
                        .HasColumnType("integer");

                    b.Property<int>("BjGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("BjLosses")
                        .HasColumnType("integer");

                    b.Property<long>("BjTotalMoneyLost")
                        .HasColumnType("bigint");

                    b.Property<long>("BjTotalMoneyWon")
                        .HasColumnType("bigint");

                    b.Property<int>("BjWins")
                        .HasColumnType("integer");

                    b.Property<int>("Blackjacks")
                        .HasColumnType("integer");

                    b.Property<string>("ClientSeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CrashGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("CrashLosses")
                        .HasColumnType("integer");

                    b.Property<long>("CrashTotalMoneyLost")
                        .HasColumnType("bigint");

                    b.Property<long>("CrashTotalMoneyWon")
                        .HasColumnType("bigint");

                    b.Property<int>("CrashWins")
                        .HasColumnType("integer");

                    b.Property<int>("DiceGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("DiceLosses")
                        .HasColumnType("integer");

                    b.Property<long>("DiceTotalMoneyLost")
                        .HasColumnType("bigint");

                    b.Property<long>("DiceTotalMoneyWon")
                        .HasColumnType("bigint");

                    b.Property<int>("DiceWins")
                        .HasColumnType("integer");

                    b.Property<int>("HiloGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("HiloLosses")
                        .HasColumnType("integer");

                    b.Property<long>("HiloTotalMoneyLost")
                        .HasColumnType("bigint");

                    b.Property<long>("HiloTotalMoneyWon")
                        .HasColumnType("bigint");

                    b.Property<int>("HiloWins")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastDaily")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastHourly")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinesGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MinesLosses")
                        .HasColumnType("integer");

                    b.Property<long>("MinesTotalMoneyLost")
                        .HasColumnType("bigint");

                    b.Property<long>("MinesTotalMoneyWon")
                        .HasColumnType("bigint");

                    b.Property<int>("MinesWins")
                        .HasColumnType("integer");

                    b.Property<string>("NextServerSeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextServerSeedHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
